# Generated by Django 6.1.1 on 2026-09-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pendingsignup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingsignup',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
